CREATE TABLE `billing_on_transaction` (
  `id` INT(12) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ch1_id` INT(12) NOT NULL,
  `payment_id` INT(12) NOT NULL,
  `billing_on_item_id` INT(12) NOT NULL,
  `demographic_no` INT(10) NOT NULL,
  `update_provider_no` VARCHAR(6) NOT NULL,
  `update_datetime` TIMESTAMP NOT NULL,
  `payment_date` DATE,
  `ref_num` VARCHAR(6),
  `province` CHAR(2),
  `man_review` CHAR(1),
  `billing_date` DATE,
  `status` CHAR(1),
  `pay_program` CHAR(3),
  `paymentType` CHAR(1),
  `facility_num` CHAR(4),
  `clinic` VARCHAR(30),
  `provider_no` VARCHAR(6),
  `creator` VARCHAR(30),
  `visittype` CHAR(2),
  `admission_date` CHAR(10),
  `sli_code` VARCHAR(10),
  `service_code` VARCHAR(10),
  `service_code_num` CHAR(2),
  `service_code_invoiced` VARCHAR(64),
  `service_code_paid` DECIMAL(10,2),
  `service_code_refund` DECIMAL(10,2),
  `service_code_discount` DECIMAL(10,2),
  `dx_code` VARCHAR(3),
  `billing_notes` VARCHAR(255)
);